apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  # tells kubectl this is a Kustomize entry point

resources:           # list of manifest files that make up the base configuration
  - deployment.yaml
  - service.yaml
